#################################
#        DATABASE SERVICE
#################################
apiVersion: v1
kind: Service
metadata:
  # this is the name we used in our Connection String
  name: db
  labels:
    app: dockerdemo
    tier: database
spec:
  type: NodePort
  ports:
  - port: 1433
    protocol: TCP
  selector:
    app: dockerdemo
    tier: database


#################################
#        DATABASE WORKLOAD
#################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    app: dockerdemo
    tier: database
spec:
  selector:
    matchLabels:
      app: dockerdemo
      tier: database
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: dockerdemo
        tier: database
    spec:
      containers:
      - name: worker
        image: microsoft/mssql-server-linux
        env:
        - name: SA_PASSWORD
          value: "Password1"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Express"