apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dockerdemo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: webbff-svc
              servicePort: 80
          - path: /
            backend:
              serviceName: webui-svc
              servicePort: 80
