version: '3.4'
services:
  ui:
    image: nvhoanganh1909/docker-demo-ui:4
    build: angular-ui/.
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
    depends_on:
      - webapi
      - db
  api-gateway:
    image:  nvhoanganh1909/apigw-base
    build: api-gateway/.
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 30003:80
    depends_on:
      - webapi
    volumes:
      - ./apiconfigs:/app/configuration
  webapi:
    image: nvhoanganh1909/docker-demo-user-api
    build: dotnetcore-webapi/.
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
  db:
    image: 'microsoft/mssql-server-linux'
    environment:
      SA_PASSWORD: 'Password1'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'